
// stores
export const START_SET_STORES = 'START_SET_STORES';
export const SET_STORES = 'SET_STORES';

// filters
export const SHOW_ALL = 'SHOW_ALL';
export const SET_FILTER = 'SET_FILTER';

// user
export const UPDATE_COLLECTION = 'UPDATE_COLLECTION';
export const START_UPDATE_COLLECTION = 'START_UPDATE_COLLECTION';
export const ADD_TO_COLLECTION = 'ADD_TO_COLLECTION';
export const START_ADD_TO_COLLECTION = 'START_ADD_TO_COLLECTION';
export const DELETE_FROM_COLLECTION = 'DELETE_FROM_COLLECTION';
export const START_DELETE_FROM_COLLECTION = 'START_DELETE_FROM_COLLECTION';

// error
export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';