
// stores
export const START_SET_STORES = 'START_SET_STORES';
export const SET_STORES = 'SET_STORES';
export const SET_STORES_LOADING = 'SET_STORES_LOADING';
export const ADD_STORES_ERROR = 'ADD_STORES_ERROR';
export const REMOVE_STORES_ERROR = 'REMOVE_STORES_ERROR';

// filters
export const SET_FILTER = 'SET_FILTER';
export const CLEAR_FILTER = 'CLEAR_FILTER';

// user
export const CREATE_COLLECTION = 'CREATE_COLLECTION';
export const START_CREATE_COLLECTION = 'START_CREATE_COLLECTION';
export const GET_COLLECTION = 'GET_COLLECTION';
export const START_GET_COLLECTION = 'START_GET_COLLECTION';
export const UPDATE_COLLECTION = 'UPDATE_COLLECTION';
export const START_UPDATE_COLLECTION = 'START_UPDATE_COLLECTION';
export const ADD_TO_COLLECTION = 'ADD_TO_COLLECTION';
export const START_ADD_TO_COLLECTION = 'START_ADD_TO_COLLECTION';
export const DELETE_FROM_COLLECTION = 'DELETE_FROM_COLLECTION';
export const START_DELETE_FROM_COLLECTION = 'START_DELETE_FROM_COLLECTION';
export const SET_USER_LOADING = 'SET_USER_LOADING';
export const SET_UPDATING_COLLECTION = 'SET_UPDATING_COLLECTION';
export const ADD_USER_ERROR = 'ADD_USER_ERROR';
export const REMOVE_USER_ERROR = 'REMOVE_USER_ERROR';
export const START_INVITE_USER = 'START_INVITE_USER';
export const INVITE_USER = 'INVITE_USER';
export const REMOVE_SUCCESS_MESSAGE = 'REMOVE_SUCCESS_MESSAGE';